FROM python:3.9.6-buster

ENV DEBUG=False
ENV PREVIEW_URL=
ENV DEPLOY_HOOK=
ENV SECRET_KEY=
ENV AWS_S3_REGION_NAME=
ENV AWS_S3_ENDPOINT_URL=
ENV AWS_STORAGE_BUCKET_NAME=
ENV AWS_ACCESS_KEY_ID=
ENV AWS_SECRET_ACCESS_KEY=

WORKDIR /app

COPY requirements.txt /app/
RUN pip install -r requirements.txt
COPY . /app/
