# Generated by Django 4.0.3 on 2022-04-05 14:03

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields
import extra_validator.field_validation.validator
import imagekit.models.fields
import website.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoPaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_type', models.CharField(choices=[('btc', 'Bitcoin'), ('eth', 'Etherium'), ('bch', 'Bitcoin Cash'), ('ltc', 'Litecoin'), ('usdt', 'Tether')], max_length=255)),
                ('wallet', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.FileField(upload_to='', verbose_name='File')),
                ('title', models.CharField(max_length=255)),
                ('title_uk', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('splash_title', models.CharField(default='Title', max_length=255)),
                ('splash_title_uk', models.CharField(default='Title', max_length=255, null=True)),
                ('splash_title_en', models.CharField(default='Title', max_length=255, null=True)),
                ('splash_text', models.TextField(default='Lorem ipsum...')),
                ('splash_text_uk', models.TextField(default='Lorem ipsum...', null=True)),
                ('splash_text_en', models.TextField(default='Lorem ipsum...', null=True)),
                ('splash_image', imagekit.models.fields.ProcessedImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Homepage',
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('text', 'Text'), ('text_image', 'Text + Image'), ('donate_cta', 'CTA + Donate button'), ('text_list', 'Numbered text list'), ('partners', 'Partners list'), ('qa', 'Questions & Answers'), ('icon_text_list', 'Icon+Text list')], max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('title_uk', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('cta', models.CharField(blank=True, max_length=255, null=True)),
                ('cta_uk', models.CharField(blank=True, max_length=255, null=True)),
                ('cta_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text', django_quill.fields.QuillField(blank=True, null=True)),
                ('text_uk', django_quill.fields.QuillField(blank=True, null=True)),
                ('text_en', django_quill.fields.QuillField(blank=True, null=True)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.homepage')),
            ],
            bases=(extra_validator.field_validation.validator.FieldValidationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uk', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('text', django_quill.fields.QuillField()),
                ('text_uk', django_quill.fields.QuillField(null=True)),
                ('text_en', django_quill.fields.QuillField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('title_uk', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('text', django_quill.fields.QuillField()),
                ('text_uk', django_quill.fields.QuillField(null=True)),
                ('text_en', django_quill.fields.QuillField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('main_image', imagekit.models.fields.ProcessedImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='WebsiteMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=255)),
                ('title_uk', models.CharField(default='Title', max_length=255, null=True)),
                ('title_en', models.CharField(default='Title', max_length=255, null=True)),
                ('description', models.TextField(default='')),
                ('description_uk', models.TextField(default='', null=True)),
                ('description_en', models.TextField(default='', null=True)),
                ('logo', models.FileField(upload_to='', validators=[website.validators.is_svg])),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('address_uk', models.TextField(null=True)),
                ('address_en', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', django_quill.fields.QuillField()),
                ('text_uk', django_quill.fields.QuillField(null=True)),
                ('text_en', django_quill.fields.QuillField(null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.pagesection')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_type', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('telegram', 'Telegram')], max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('meta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.websitemeta')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('question_uk', models.CharField(max_length=255, null=True)),
                ('question_en', models.CharField(max_length=255, null=True)),
                ('answer', models.TextField()),
                ('answer_uk', models.TextField(null=True)),
                ('answer_en', models.TextField(null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.pagesection')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=255)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.pagesection')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', imagekit.models.fields.ProcessedImageField(upload_to='')),
                ('alt', models.CharField(blank=True, max_length=255, null=True)),
                ('alt_uk', models.CharField(blank=True, max_length=255, null=True)),
                ('alt_en', models.CharField(blank=True, max_length=255, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.post')),
            ],
        ),
        migrations.CreateModel(
            name='IconTextItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='', validators=[website.validators.is_svg])),
                ('title', models.CharField(max_length=255)),
                ('title_uk', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('summary', models.TextField()),
                ('summary_uk', models.TextField(null=True)),
                ('summary_en', models.TextField(null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('details_uk', models.TextField(blank=True, null=True)),
                ('details_en', models.TextField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.pagesection')),
            ],
        ),
    ]
