# Generated by Django 4.0.3 on 2022-05-17 06:44

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields
import imagekit.models.fields
import website.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('src', models.FileField(upload_to='', verbose_name='File')),
                ('title', models.CharField(max_length=255)),
                ('title_uk', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('splash_title', models.CharField(default='Title', max_length=255)),
                ('splash_title_uk', models.CharField(default='Title', max_length=255, null=True)),
                ('splash_title_en', models.CharField(default='Title', max_length=255, null=True)),
                ('splash_text', models.TextField(default='Lorem ipsum...')),
                ('splash_text_uk', models.TextField(default='Lorem ipsum...', null=True)),
                ('splash_text_en', models.TextField(default='Lorem ipsum...', null=True)),
                ('splash_image', imagekit.models.fields.ProcessedImageField(upload_to='')),
                ('intro_text', django_quill.fields.QuillField(blank=True, null=True)),
                ('intro_text_uk', django_quill.fields.QuillField(blank=True, null=True)),
                ('intro_text_en', django_quill.fields.QuillField(blank=True, null=True)),
                ('intro_image', imagekit.models.fields.ProcessedImageField(upload_to='')),
                ('intro_text_2', django_quill.fields.QuillField(blank=True, null=True)),
                ('intro_text_2_uk', django_quill.fields.QuillField(blank=True, null=True)),
                ('intro_text_2_en', django_quill.fields.QuillField(blank=True, null=True)),
                ('wartime_image', imagekit.models.fields.ProcessedImageField(upload_to='')),
                ('peacetime_image', imagekit.models.fields.ProcessedImageField(upload_to='')),
                ('cta', models.CharField(blank=True, max_length=255, null=True)),
                ('cta_uk', models.CharField(blank=True, max_length=255, null=True)),
                ('cta_en', models.CharField(blank=True, max_length=255, null=True)),
                ('outro_text', django_quill.fields.QuillField(blank=True, null=True)),
                ('outro_text_uk', django_quill.fields.QuillField(blank=True, null=True)),
                ('outro_text_en', django_quill.fields.QuillField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Homepage',
            },
        ),
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_of_use_enabled', models.BooleanField(default=False)),
                ('terms_of_use', django_quill.fields.QuillField(blank=True, null=True)),
                ('terms_of_use_uk', django_quill.fields.QuillField(blank=True, null=True)),
                ('terms_of_use_en', django_quill.fields.QuillField(blank=True, null=True)),
                ('privacy_policy_enabled', models.BooleanField(default=False)),
                ('privacy_policy', django_quill.fields.QuillField(blank=True, null=True)),
                ('privacy_policy_uk', django_quill.fields.QuillField(blank=True, null=True)),
                ('privacy_policy_en', django_quill.fields.QuillField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liqpay_link', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('title_uk', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('text', django_quill.fields.QuillField(default='')),
                ('text_uk', django_quill.fields.QuillField(default='', null=True)),
                ('text_en', django_quill.fields.QuillField(default='', null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('main_image', imagekit.models.fields.ProcessedImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='WebsiteMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=255)),
                ('title_uk', models.CharField(default='Title', max_length=255, null=True)),
                ('title_en', models.CharField(default='Title', max_length=255, null=True)),
                ('description', models.TextField(default='')),
                ('description_uk', models.TextField(default='', null=True)),
                ('description_en', models.TextField(default='', null=True)),
                ('logo', models.FileField(upload_to='', validators=[website.validators.is_svg])),
                ('logo_inverted', models.FileField(upload_to='', validators=[website.validators.is_svg])),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('address', django_quill.fields.QuillField(default='')),
                ('address_uk', django_quill.fields.QuillField(default='', null=True)),
                ('address_en', django_quill.fields.QuillField(default='', null=True)),
                ('copyright', models.CharField(default='© BNC, 2022', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WartimeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('icon', models.FileField(upload_to='', validators=[website.validators.is_svg])),
                ('title', models.CharField(max_length=255)),
                ('title_uk', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('text', django_quill.fields.QuillField(default='')),
                ('text_uk', django_quill.fields.QuillField(default='', null=True)),
                ('text_en', django_quill.fields.QuillField(default='', null=True)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wartime_items', to='website.homepage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('text', models.CharField(max_length=255)),
                ('text_uk', models.CharField(max_length=255, null=True)),
                ('text_en', models.CharField(max_length=255, null=True)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_we_help', to='website.homepage')),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('social_type', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('telegram', 'Telegram')], max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('meta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.websitemeta')),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PeacetimeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('icon', models.FileField(upload_to='', validators=[website.validators.is_svg])),
                ('title', models.CharField(max_length=255)),
                ('title_uk', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('text', django_quill.fields.QuillField(default='')),
                ('text_uk', django_quill.fields.QuillField(default='', null=True)),
                ('text_en', django_quill.fields.QuillField(default='', null=True)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peacetime_items', to='website.homepage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('title_uk', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('text', django_quill.fields.QuillField(default='')),
                ('text_uk', django_quill.fields.QuillField(default='', null=True)),
                ('text_en', django_quill.fields.QuillField(default='', null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.payment')),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=255)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='website.homepage')),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('src', imagekit.models.fields.ProcessedImageField(upload_to='')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.post')),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CryptoPaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('crypto_type', models.CharField(choices=[('btc', 'Bitcoin'), ('eth', 'Etherium'), ('bch', 'Bitcoin Cash'), ('ltc', 'Litecoin'), ('usdt', 'Tether')], max_length=255)),
                ('wallet', models.CharField(max_length=255)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.payment')),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
    ]
