# Generated by Django 4.0.3 on 2022-04-09 18:48

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitemeta',
            name='address',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='websitemeta',
            name='address_en',
            field=django_quill.fields.QuillField(null=True),
        ),
        migrations.AlterField(
            model_name='websitemeta',
            name='address_uk',
            field=django_quill.fields.QuillField(null=True),
        ),
    ]
