# Generated by Django 4.0.3 on 2022-05-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='splash_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='splash_text_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='splash_text_uk',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='splash_title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='splash_title_en',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='splash_title_uk',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='websitemeta',
            name='copyright',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='websitemeta',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='websitemeta',
            name='title_en',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='websitemeta',
            name='title_uk',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
