# Generated by Django 4.0.3 on 2022-04-09 11:21

from django.db import migrations, models
import website.validators


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitemeta',
            name='logo_inverted',
            field=models.FileField(default=None, upload_to='', validators=[website.validators.is_svg]),
            preserve_default=False,
        ),
    ]
