# Generated by Django 4.0.3 on 2022-04-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_websitemeta_logo_inverted'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitemeta',
            name='copyright',
            field=models.CharField(default='© BNC, 2022', max_length=255),
        ),
    ]
