# Generated by Django 4.0.3 on 2022-05-26 11:37

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_websitemeta_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legal',
            name='privacy_policy',
            field=django_quill.fields.QuillField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='legal',
            name='privacy_policy_en',
            field=django_quill.fields.QuillField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='legal',
            name='privacy_policy_uk',
            field=django_quill.fields.QuillField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='legal',
            name='terms_of_use',
            field=django_quill.fields.QuillField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='legal',
            name='terms_of_use_en',
            field=django_quill.fields.QuillField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='legal',
            name='terms_of_use_uk',
            field=django_quill.fields.QuillField(blank=True, default='', null=True),
        ),
    ]
