# Generated by Django 4.0.3 on 2022-04-11 12:32

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_delete_cryptopaymentdetail_delete_paymentdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uk', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('text', django_quill.fields.QuillField(default='')),
                ('text_uk', django_quill.fields.QuillField(default='', null=True)),
                ('text_en', django_quill.fields.QuillField(default='', null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.payment')),
            ],
        ),
        migrations.CreateModel(
            name='CryptoPaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_type', models.CharField(choices=[('btc', 'Bitcoin'), ('eth', 'Etherium'), ('bch', 'Bitcoin Cash'), ('ltc', 'Litecoin'), ('usdt', 'Tether')], max_length=255)),
                ('wallet', models.CharField(max_length=255)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.payment')),
            ],
        ),
    ]
