# Generated by Django 4.0.3 on 2022-05-29 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_payment_liqpay_link_payment_liqpay_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='liqpay_enabled',
        ),
    ]
