# Generated by Django 4.0.3 on 2022-04-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_payment_paymentdetail_cryptopaymentdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='liqpay_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
