# Generated by Django 4.0.3 on 2022-04-12 07:57

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_payment_liqpay_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_of_use_enabled', models.BooleanField(default=False)),
                ('term_of_use', django_quill.fields.QuillField(blank=True, null=True)),
                ('term_of_use_uk', django_quill.fields.QuillField(blank=True, null=True)),
                ('term_of_use_en', django_quill.fields.QuillField(blank=True, null=True)),
                ('privacy_policy_enabled', models.BooleanField(default=False)),
                ('privacy_policy', django_quill.fields.QuillField(blank=True, null=True)),
                ('privacy_policy_uk', django_quill.fields.QuillField(blank=True, null=True)),
                ('privacy_policy_en', django_quill.fields.QuillField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
