# Generated by Django 4.0.3 on 2022-04-12 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_legal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legal',
            old_name='term_of_use',
            new_name='terms_of_use',
        ),
        migrations.RenameField(
            model_name='legal',
            old_name='term_of_use_en',
            new_name='terms_of_use_en',
        ),
        migrations.RenameField(
            model_name='legal',
            old_name='term_of_use_enabled',
            new_name='terms_of_use_enabled',
        ),
        migrations.RenameField(
            model_name='legal',
            old_name='term_of_use_uk',
            new_name='terms_of_use_uk',
        ),
    ]
