# Generated by Django 4.0.3 on 2022-04-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_rename_term_of_use_legal_terms_of_use_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='image_on_the_left',
            field=models.BooleanField(default=False),
        ),
    ]
