# Generated by Django 4.0.3 on 2022-04-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_pagesection_image_on_the_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
