# Generated by Django 4.0.3 on 2022-04-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_pagesection_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptopaymentdetail',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='icontextitem',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='pagesection',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='paymentdetail',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='textitem',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='cryptopaymentdetail',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='icontextitem',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partner',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textitem',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
